#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

# Execute your tests as shell commands below. 
# An exit code of zero signals success, any other code signals an error
# and causes this test to fail.
# See https://github.com/tlevine/urchin.

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "ERROR: $*" >&2; exit 1; }

# Choose unknown option.
opt=-Z

# Test both direct-invocation and sourced scenarios, as well as combinations with valid options and operands.
cmds=( "typex $opt" ". typex $opt" "typex typex $opt" "typex -v $opt" )

for cmd in "${cmds[@]}"; do
  eval "$cmd" && die "Unexpectedly succeeded despite unknown option '$opt'."
done

exit 0
