#!/usr/bin/env dash

PATH="../../bin:$PATH"

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "ERROR: $*" >&2; exit 1; }

shell=$(ps -o comm= $$)

. typex && die "Argument-less sourcing in unsupported shell succeeded unexpectedly: $shell"
. typex -p typex && die "Sourcing with arguments in unsupported shell succeeded unexpectedly: shell"

exit 0
